version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "Gen code from proto file"
    cmds:
      - protoc -I proto ./proto/products/products.proto --go_out gen/ --go_opt=paths=source_relative --go-grpc_out=gen/ --go-grpc_opt=paths=source_relative